services:

  seg_and_track:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: services/seg_and_track/Dockerfile
    restart: always
    volumes:
      - ./common_packages:/common_packages
    networks:
      - assistant-network

networks:
  assistant-network:
    driver: bridge

volumes:
  intent_catcher_data:
